version: '2'
services:
  blog-web-server:
    build: blog
    ports:
      - "5085:80"
    volumes:
      - ./blog/:/var/www/html    
    links:
      - db
  db:
    image: mysql:5.7
    ports:
     - 3301:3306
    volumes:
     - ./mysql5.7:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=mysql123
     - MYSQL_DATABASE=laravel_demo
     - MYSQL_USER=dbuser1
     - MYSQL_PASSWORD=mysql123
